### ISSUE TITLE
Feature: Punch IN/OUT

### ISSUE THREAD

**Issue by danielbair** [orangehrm/orangehrm-os-mobile#35]
Please add Punch IN/OUT to the os mobile app.

**Comment by samanthajayasinghe** [comment]
Hi @danielbair,
Thanks for your request.
 It's in our roadmap and will release the feature before the end of this year.

**Comment by RajithaKumara** [comment]
Hi @danielbair 
You can now try out Mobile 2.0.0 release with [OrangeHRM 4.7 release](https://sourceforge.net/projects/orangehrm/files/stable/4.7/).
