### ISSUE TITLE
Release standalone APK

### ISSUE THREAD

**Issue by nototbol** [orangehrm/orangehrm-os-mobile#42]
Many users have smartphone without Google Play support. Publish APK is option to install OrangeHRM mobile on these smartphones.

**Comment by RajithaKumara** [comment]
Hi @nototbol,
Sorry for addressing this after long time.
We have attached Signed APKs to each Github release [here](https://github.com/orangehrm/orangehrm-os-mobile/releases).
Also you can download the latest APK from the website as well https://www.orangehrm.com/en/orangehrm-starter-open-source-software/ . There is a button as "APK DOWNLOAD" under "Mobile App" section.
