### ISSUE TITLE
A problem occurred evaluating project ':react-native-gesture-handler'.

### ISSUE THREAD

**Issue by SachiyaTZ** [orangehrm/orangehrm-os-mobile#50]
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file '\node_modules\react-native-gesture-handler\android\build.gradle' line: 55

* What went wrong:
A problem occurred evaluating project ':react-native-gesture-handler'.
> Could not initialize class org.jetbrains.kotlin.gradle.plugin.KotlinGradleBuildServices

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s

**Comment by RajithaKumara** [comment]
Hi @SachiyaTZ 
Please provide the git HEAD hash. So we can understand the version
